// <auto-generated />
using System;
using BusTrackingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusTrackingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528113709_AddPickupAlreadyPassedNotification")]
    partial class AddPickupAlreadyPassedNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusTrackingAPI.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new TimeSpan(0, 5, 0, 0, 0),
                            DeviceId = "SIM808_01",
                            IsActive = true,
                            Name = "Strugë - Tetovë - Shkup 05:00",
                            PlateNumber = "BUS-0500",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 2,
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Strugë - Tetovë - Shkup 08:00",
                            PlateNumber = "BUS-0800",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 3,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Strugë - Tetovë - Shkup 12:00",
                            PlateNumber = "BUS-1200",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 4,
                            DepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Shkup - Strugë 11:00",
                            PlateNumber = "BUS-1100",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 5,
                            DepartureTime = new TimeSpan(0, 13, 15, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Shkup - Strugë 13:15",
                            PlateNumber = "BUS-1315",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 6,
                            DepartureTime = new TimeSpan(0, 16, 20, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Shkup - Strugë 16:20",
                            PlateNumber = "BUS-1620",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 7,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Tetovë - Strugë 12:00",
                            PlateNumber = "BUS-T1200",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 8,
                            DepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Tetovë - Strugë 14:15",
                            PlateNumber = "BUS-T1415",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 9,
                            DepartureTime = new TimeSpan(0, 17, 20, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Tetovë - Strugë 17:20",
                            PlateNumber = "BUS-T1720",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 10,
                            DepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Strugë - Tetovë - Shkup 17:00 Monday/Friday/Sunday",
                            PlateNumber = "BUS-1700",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 11,
                            DepartureTime = new TimeSpan(0, 21, 0, 0, 0),
                            DeviceId = "",
                            IsActive = true,
                            Name = "Shkup - Strugë 21:00 Monday/Friday/Sunday",
                            PlateNumber = "BUS-2100",
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("Signal")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("BusLocations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "UserId", "ReservationId", "Type")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupPlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("BusId", "SeatNumber", "ReservationDate")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Bus", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.User", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusLocation", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Bus", "Bus")
                        .WithMany("Locations")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Notification", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BusTrackingAPI.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTrackingAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Reservation", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Bus", "Bus")
                        .WithMany("Reservations")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTrackingAPI.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Trip", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Bus", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
