// <auto-generated />
using System;
using BusTrackingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusTrackingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusTrackingAPI.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartureTime = new TimeSpan(0, 5, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 1",
                            PlateNumber = "BUS-0500",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 2,
                            DepartureTime = new TimeSpan(0, 8, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 2",
                            PlateNumber = "BUS-0800",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 3,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 3",
                            PlateNumber = "BUS-1200",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 4,
                            DepartureTime = new TimeSpan(0, 11, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 4",
                            PlateNumber = "BUS-1100",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 5,
                            DepartureTime = new TimeSpan(0, 13, 15, 0, 0),
                            IsActive = true,
                            Name = "Bus 5",
                            PlateNumber = "BUS-1315",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 6,
                            DepartureTime = new TimeSpan(0, 16, 20, 0, 0),
                            IsActive = true,
                            Name = "Bus 6",
                            PlateNumber = "BUS-1620",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 7,
                            DepartureTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 7",
                            PlateNumber = "BUS-T1200",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 8,
                            DepartureTime = new TimeSpan(0, 14, 15, 0, 0),
                            IsActive = true,
                            Name = "Bus 8",
                            PlateNumber = "BUS-T1415",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 9,
                            DepartureTime = new TimeSpan(0, 17, 20, 0, 0),
                            IsActive = true,
                            Name = "Bus 9",
                            PlateNumber = "BUS-T1720",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 10,
                            DepartureTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 10",
                            PlateNumber = "BUS-1700",
                            TotalSeats = 40
                        },
                        new
                        {
                            Id = 11,
                            DepartureTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            Name = "Bus 11",
                            PlateNumber = "BUS-2100",
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("Signal")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("TripId");

                    b.ToTable("BusLocations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ExpectedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Skopje",
                            ExpectedDurationMinutes = 180,
                            IsActive = true,
                            Name = "Struga - Tetovo - Skopje",
                            Origin = "Struga"
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Struga",
                            ExpectedDurationMinutes = 180,
                            IsActive = true,
                            Name = "Skopje - Tetovo - Struga",
                            Origin = "Skopje"
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Struga",
                            ExpectedDurationMinutes = 120,
                            IsActive = true,
                            Name = "Tetovo - Struga",
                            Origin = "Tetovo"
                        });
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("integer");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "UserId", "ReservationId", "Type")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<double>("PickupLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("PickupLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PickupPlaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "SeatNumber")
                        .IsUnique()
                        .HasFilter("\"TripId\" IS NOT NULL");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusLocation", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Bus", "Bus")
                        .WithMany("Locations")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTrackingAPI.Models.Trip", "Trip")
                        .WithMany("Locations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bus");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Notification", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BusTrackingAPI.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTrackingAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Reservation", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Trip", "Trip")
                        .WithMany("Reservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusTrackingAPI.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Trip", b =>
                {
                    b.HasOne("BusTrackingAPI.Models.Bus", "Bus")
                        .WithMany("Trips")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTrackingAPI.Models.User", "Driver")
                        .WithMany("DrivenTrips")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BusTrackingAPI.Models.BusRoute", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bus");

                    b.Navigation("Driver");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Bus", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.BusRoute", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.Trip", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BusTrackingAPI.Models.User", b =>
                {
                    b.Navigation("DrivenTrips");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
